"""empty message

Revision ID: ca33152d4cde
Revises: b9ed4adc02c0
Create Date: 2023-03-10 14:31:19.038758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca33152d4cde'
down_revision = 'b9ed4adc02c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=False))
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###